### ISSUE TITLE
Transitioning from Account 1 to Account 2 in MNS does not reflect in the interface

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#17]
Transitioning from Account 1 to Account 2 in MNS does not reflect in the interface. Even after Metamask switches to Account 2, MNS continues to display Account 1.

**Comment by hairyf** [comment]
If you only switch accounts without connecting, you will not be able to monitor account changes


![Image](https://github.com/MXCzkEVM/mns-app/assets/49724027/9196afb9-9399-4fa9-a67a-ed003c1b6f7f)

**Comment by SanghamitraBhowmick1993** [comment]
working as expected
