### ISSUE TITLE
account profile image by MNS

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/mns-app#19]
https://www.notion.so/wannsee-roadmap/account-profile-image-by-MNS-60bafdada0c1424a8d2dbcd4f90213c8

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993 Fixed


![Image](https://github.com/MXCzkEVM/mns-app/assets/49724027/2ef1051b-6ab4-4791-9265-c8fb050ee62f)

Now you can try modifying your avatar in geneva

**Comment by SanghamitraBhowmick1993** [comment]
This is working as expected. 

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/bf11f792-f09b-4e05-b374-6ac064e84e3f)
