### ISSUE TITLE
When connecting my account, I still see Metamask listed as the primary option instead of AXS for MNS - Geneva

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/mns-app#20]
When connecting my account, I still see Metamask listed as the primary option instead of AXS for MNS - Geneva

![image](https://github.com/MXCzkEVM/mns-app/assets/93600163/42358f5b-9bd4-48c4-93a6-49e596d8c176)

**Comment by hairyf** [comment]
Rainbowkit will record the most recent connection methods used, which is a normal phenomenon. Please ensure that the cache is cleared

**Comment by hairyf** [comment]
Rainbowkit will record recent wallet connections, which is a normal phenomenon and cannot be changed. Please ensure that the cache is cleared

**Comment by SanghamitraBhowmick1993** [comment]
ok i will test more on this on the mobile app, closing this for now!
