### ISSUE TITLE
I bought a second MNS name in geneva for address 0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A, the tx was successful, but i was not able to see the new name in MNS dapp

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#22]
I bought a second MNS name in geneva for address 0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A, the tx was successful, but i was not able to see the new name in MNS dapp https://geneva-mns.moonchain.com/my/names?sort=labelName
tx: https://geneva-explorer.moonchain.com/tx/0xbf6526b1bb4c199532b46bb7afbb0a52287248ebad63088ed4a650aa6e172ac8

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/a47dfcb8-d757-497f-9173-27c2bbabab85)

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/11f7de9c-096e-41b7-99ca-f49d79ce8c28)

**Comment by SanghamitraBhowmick1993** [comment]
I am able to see all MNS names(working), but i can not see another MNS Name as primary name. WHen i click 'Set as primary name' and click open wallet i get an unknown error


![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/946a7be6-a07f-4c0b-a2c9-164c26277e6e)
