### ISSUE TITLE
Even after acquiring an MNS name, the 'Acquiring 1 MNS' task still appears in red instead of green

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#23]
![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/bed85835-ff9a-463d-a0f8-05ab0ad4aa91)

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/3c42b2eb-1ab0-4548-8a74-c38226f72cc8)

**Comment by sheenhx** [comment]
Wannsee tasks will remain, add Geneva tasks with the same scope

**Comment by SanghamitraBhowmick1993** [comment]
I am still unable to see the task completed for Geneva
https://airdrop.moonchain.com/address/0x58B67d40A4C0488e20389ad5aE2F033D4235900a


![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/aa6ca831-6f51-4f47-85d5-4617b0498904)



![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/80b863f7-9586-4b4b-a879-d60f631fb0b1)

**Comment by SanghamitraBhowmick1993** [comment]
Is it normal to find the task "Bridging funds into Wannsee Testnet" under the airdrop section? Additionally, the task "Acquiring 1 MNS" still appears in red.

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/123f3dad-7b4f-4a14-a47d-96a32326f82a)

**Comment by SanghamitraBhowmick1993** [comment]
Should we still continue to display tasks for Wannsee within airdrop?


![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/fad00793-7166-4cc2-9cbb-3b6652d88835)

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993  yes
