### ISSUE TITLE
Unable to Set Primary MNS Name; Unknown Error Occurs When Attempting to Open Wallet

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#24]
I bought a second MNS name in geneva for address 0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A, the tx was successful, but i was not able to see the new name in MNS dapp https://geneva-mns.moonchain.com/my/names?sort=labelName
tx: https://geneva-explorer.moonchain.com/tx/0xbf6526b1bb4c199532b46bb7afbb0a52287248ebad63088ed4a650aa6e172ac8

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/86d62ec0-5991-43d9-a2b5-57bc6b6df3e2)

**Comment by SanghamitraBhowmick1993** [comment]
working as expected

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/d3ae00de-4007-42c3-bb72-4885b051379a)
