### ISSUE TITLE
Question: MNS name confirmation

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#25]
Can you confirm if the name is correct for the MNS testnet? I noticed "zkevm" mentioned and I'm unsure if this is expected.

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/287b0f19-1510-4692-a407-4e03accebdd6)

**Comment by hairyf** [comment]
modified name

**Comment by SanghamitraBhowmick1993** [comment]
This is working 

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/a647bebc-7058-47da-aeae-b2e7e8bce6fb)
